FROM yankovg/python3.8.2-ubuntu18.04:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y \
    git \
    openssh-server \
    liblzma-dev \
    libbz2-dev

# timezone
RUN export DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata

# python recompile (_bz error, lzma warning)
RUN wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz
RUN tar xvfz Python-3.8.2.tgz
WORKDIR /Python-3.8.2
RUN ./configure --enable-optimizations
RUN make
RUN make install

# default python version set
RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.8 1

COPY .env .
RUN source .env && \
    echo "export PYTHONPATH=${PYTHONPATH}" >> ~/.profile && \
    echo "export MONGODB_URL=${MONGODB_URL}" >> ~/.profile && \
    echo "export REDIS_HOST_IP=${REDIS_HOST_IP}" >> ~/.profile && \
    echo "export CELERY_BROKER_URL=${CELERY_BROKER_URL}" >> ~/.profile && \
    echo "export CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}" >> ~/.profile && \
    echo "export C_FORCE_ROOT=${C_FORCE_ROOT}" >> ~/.profile && \
    echo "export LC_ALL=${LC_ALL}" >> ~/.profile && \
    echo "export LANG=${LANG}" >> ~/.profile

# pip install list
COPY ./flask/requirements.txt .
RUN pip install -r requirements.txt

#set password
RUN echo 'root:root'|chpasswd

#replace sshd_config
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

#make .ssh
RUN mkdir /root/.ssh
RUN service ssh start
