version: '3.3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ${SACRED_DATABASE_PATH}:/data/db
    env_file: 
      - .env
    networks:
      - omniboard

  omniboard:
    image: omniboard:release
    build: 
      context: ./omniboard
      dockerfile: dockerfile
    ports:
      - '9000:9000'
    networks:
      - omniboard
    depends_on:
      - mongo

networks:
  omniboard:
