FROM silverlogic/python3.8

SHELL ["/bin/bash", "-c"]
RUN echo "alias ll='ls $LS_OPTIONS -l'" >> ~/.bashrc && source ~/.bashrc

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y git \
        openssh-server \
        liblzma-dev \
        libbz2-dev

# timezone
RUN export DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata

COPY .env .
RUN source .env && \
    echo "export PYTHONPATH=${PYTHONPATH}" >> ~/.profile && \
    echo "export MONGODB_URL=${MONGODB_URL}" >> ~/.profile && \
    echo "export REDIS_HOST_IP=${REDIS_HOST_IP}" >> ~/.profile && \
    echo "export CELERY_BROKER_URL=${CELERY_BROKER_URL}" >> ~/.profile && \
    echo "export CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}" >> ~/.profile && \
    echo "export C_FORCE_ROOT=${C_FORCE_ROOT}" >> ~/.profile && \
    echo "export FASTAPI_PORT=${FASTAPI_PORT}" >> ~/.profile \
    echo "export REDIS_SUBSCRIBE_CHANNEL=${REDIS_SUBSCRIBE_CHANNEL}" >> ~/.profile \
    echo "export LC_ALL=${LC_ALL}" >> ~/.profile && \
    echo "export LANG=${LANG}" >> ~/.profile

# pip install list
COPY ./fastapi/requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

#set password
RUN echo 'root:root'|chpasswd

#replace sshd_config
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

#make .ssh
RUN mkdir /root/.ssh
RUN service ssh start
