services:
  mongo_db:
    image: mongo
    container_name: mongodb_dev
    ports:
      - 37017:27017
    env_file:
      - .env
    volumes:
      - ${MONGODB_PATH}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
 
