version: '3.3'

services:
  client:
    image: client:test
    env_file:
      - .env
    volumes:
      - /workflow:/workflow
      - /tmp:/tmp
      - ${MLFLOW_RUNS_PATH}:/mlruns

  server:
    image: server:test
    env_file:
      - .env
    volumes:
      - /workflow:/workflow
      - /tmp:/tmp
      - ${MLFLOW_RUNS_PATH}:/mlruns
