version: '3.3'

services:
  sklearn:
    image: sklearn:release
    env_file:
      - .env
    volumes:
      - workflow:/workflow
      - /tmp:/tmp
      - ${MLFLOW_RUNS_PATH}:/mlruns

  fastapi:
    image: fastapi:release
    env_file:
      - .env
    volumes:
      - /workflow:/workflow
      - /tmp:/tmp
      - ${MLFLOW_RUNS_PATH}:/mlruns
