FROM pytorch/pytorch:latest

# timezone
RUN export DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN apt-get update && apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata

# pip install list
RUN pip install pandas
RUN pip install numpy
RUN pip install seaborn
RUN pip install jupyter
RUN pip install onnx onnxruntime
RUN pip install torchtext
