services:
  pytorch:
    image: pytorch:2.3.0
    container_name: pytorch_dev
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - /workflow:/workflow
    ports:
      - '22222:22'
      - '8889:8888'
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command:
      - /bin/bash
      - -c
      - |
        /usr/sbin/sshd -D
